#!/bin/bash

# Set Pyenv installation directory
export PYENV_ROOT="$HOME/.pyenv"

# Check if Pyenv is installed
if ! command -v pyenv >/dev/null 2>&1; then
    echo "Installing Pyenv and dependencies..."

    # Create necessary directories
    mkdir -p ~/.local/bin

    # Install required dependencies
    sudo apk add --no-cache git bash pipx py3-pip build-base libffi-dev openssl-dev bzip2-dev zlib-dev xz-dev readline-dev sqlite-dev tk-dev


    # Clone Pyenv repository
    git clone https://github.com/pyenv/pyenv.git "$PYENV_ROOT"

    # Build Pyenv
    cd "$PYENV_ROOT" && src/configure && make -C src && cd - >/dev/null

    # Fix ownership (not needed in most cases, but added for completeness)
    chown -R "$(whoami)" "$PYENV_ROOT"

    # Initialize Pyenv
    export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init --path)"

    # Install and set Python version
    pyenv install 3.12
    pyenv global 3.12
    pipx ensurepath
    pipx install pipenv

    # Install pipenv
    pipx install pipenv
fi

